### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by lanh97** [kordaniel/oskari#1]
klo 22:33 8.4.2019

Ohjelma näyttää hyvältä päällisin puolin. On paljon toimivia toiminnallisuuksia ja suurin osa käyttötapauksista saa tehtyä. Yhteenveto- ja ryhmä ominaisuus ovat varmaan tulossa. 

Acheckerilla katoin ja html sivut ovat kunnossa. 

Koodi näyttää siistiltä ja pakkaukset on hyvin jaeteltu omiin kansioihin. Toiminnallisuuksia on hyvä määrä ja huomaan, että sulla on hyvä ohjelmointirutiini commiteista.

#Käyttäjäkokemukseni
Ensiksi olin rekisteröitymätön ja pääsin katsomaan osakelistaa. Sitten klikkasin osaketta pääsin osakkeen update sivulle. En tietenkään päässyt päivittämään osaketta, vaan ohjasi minut login sivulle. Tämän jälkeen menin rekisteröimään itseni. Rekisteröinnissä oli hyvin valittu validoinnit ja se tuntui kuin olisi rekisteröimässä oikeaan sivuun. Kirjautuneena sain nähdä lisää välilehtiä ja painoin "add a stock":ia. Pääsin ihan normaalisti lisäämään osakkeen listaan ja osakkeen listaus sivulta pääsin päivittämään sitä. Tästä jatkoin salkun lisäykseen ja tästä menin lisäämään osakkeita salkkuun.  Kun yritin lisätä virheellisen osakkeen, niin se ei lisännyt sitä. Tästä huomaan, että tietokannat pelaa.  Sitten menin ja suljin kaupan.  Oman profiilisivulla näin kaikki omat salkut. 

Olet valinnut mielenkiintoisen aiheen ja aiheen toteutus on hyvä. Olet saanut paljon toiminnallisuuksia toimimaan ja käyttökokemus oli hyvä.  Uskon, että saat korkean arvosanan, jos jatkan samaan tahtiin. Tsemppiä ja onnea jatkoon.

**Comment by kordaniel** [comment]
Kiitoksia hyvästä katselmoinnista! Toivottavasti saat vielä oman projektisi loppuun myös, huutokauppa on mielenkiintoinen aihe :)
