### ISSUE TITLE
Koodikatselmointi 2

### ISSUE THREAD

**Issue by robertrantanen** [kordaniel/oskari#2]
Projekti ladattu 27.4 klo 16.13

Kaiken kaikkiaan projekti on paljon edistyneempi kuin omani, joten minun on vaikeaa keksiä siihen parannusehdotuksia. Luokkien, metodien ja muuttujien nimentä on selkeätä ja kuvaavaa, tästä ei mitään moitittavaa. Osakekauppa ei ole minulle tuttua, joten sovelluksen logiikkaa oli aika hankalaa ymmärtää, mutta dokumentaatio auttoi.

Seikkailin sovelluksessa paikallisesti ja pystyin luomaan uuden käyttäjän sekä osakkeita ja salkkuja. Salkkunäkymässä syötin jotain kenttiin ja painoin nappeja, en oikein ymmärtänyt mitä tapahtui mutta vaikutti toimivan. Add new stock-toiminto pysähtyy virheviestiin jos yritetään lisätä uusi osake olemassaolevalla Ticker-parametrilla. Tämän voi luultavasti estää helposti validioinnilla, samalla tavalla kuin uuden käyttäjän luomisessa.

![Screenshot from 2019-04-28 18-19-50](https://user-images.githubusercontent.com/43168856/56867417-9fc27e00-69ed-11e9-9cec-0ba4edd18399.png)

Käyttäjät pääsevät näkemään linkkejä ja sivuja joihin heillä ei luultavasti ole asiaa. Esimerkiksi rekisteröitymätön käyttäjä pääsee List stocks-näkymässä klikkaamaan osakkeen yrityksen nimeä ja siirtymään muokkausnäkymään. Muokkaaminen kuitenkin tyssää kirjautumispyyntöön, mutta olisi varmaankin kätevämpää estää rekisteröitymättömän käyttäjän pääsy kyseiseen näkymään.

List Portfolios-näkymässä kirjautunut normaalikäyttäjä voi nähdä muiden käyttäjien salkkuja, mutta toisen käyttäjän salkun klikkaaminen tuo eteen kirjautumisnäkymän. Kirjautumisnäkymän sijasta olisi varmaankin kätevämpää estää linkin klikkaaminen. Toisaalta, ylläpitokäyttäjä taas pääsee sisään toisten salkkuihin. Ehkä normaalikäyttäjänkin pitäisi? Tai ylläpitokäyttäjän ei pitäisi? en ole yhtään varma mikä on tarkoituksenmukaista.

Ylläpitokäyttäjä pääsee toisten käyttäjien salkuissa klikkaamaan back to profile-linkkiä, mikä tuo taas eteen kirjautumisnäkymän. Linkin klikkaamisen estäminen olisi tässäkin tapauksessa kätevämpää, tai ehkäpä pitäisi vain sallia pääsy profiiliin.

Kuka tahansa käyttäjä pääsee muokkaamaan minkä tahansa osakkeen yrityksen nimeä, ehkäpä tämä toiminto pitäisi rajoittaa vain ylläpitokäyttäjiin ja käyttäjään joka on luonut kyseisen osakkeen?

Käyttäjän poistaminen ei toimi jos tällä on salkkuja, tästä mainittiinkin dokumentaatiossa.

**Comment by kordaniel** [comment]
Kiitoksia hyvästä katselmoinnista! Todella hyviä huomioita toit esille! Valitettavasti sovellus taisi olla salkkusivun osalta hieman ns. "vaiheessa" loppuviikon/viikonlopun aikana. Nyt pitäisi toivottavasti olla hieman selkeämpi.

Tästä kyllä oppii, että ei kannata keskeneräistä koodia pushata githubiin, jollei siihen ole erittäin painavaa syytä. Etenkään, kun se vielä menee automaattisesti herokuun, vaikka sinä testasitkin paikallisesti. Oikeastaan pitäisi opetella käyttämään GITin haaroja varmaan. :)

Osakkeiden lisäämisestä on tosiaan unohtunut validointi, vaikka olin ihan varma että olin sen lisännyt, korjataan! :) Suurin osa muista esilletuomistasi huomioista on jo korjattu, helppo korjailla kun vain seuraa ehdotuksiasi! Loput pyrin vielä myös tietenkin korjaamaan ja täten suljen tämän issuen nyt.
